#!/usr/bin/env bash

clear
echo "Informação muito importante"
echo "----------------------------------------"

echo -n "Usuário: "
whoami

echo -n "Hostname: "
hostname

echo -n "Uptime: "
uptime -p

echo -n "Kernel: "
uname -rms

echo "----------------------------------------"
echo ""

